insertMissingContractYears(2018,
                           "P.K. Subban",
                           "D",
                           "",
                           25,
                           5,
                           8,
                           72000000,
                           2022,
                           "montreal",
                           2014,
                           "$9,000,000",
                           9000000,
                           9000000,
                           4)

